name: Working Branches

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches: [ develop ]
      
jobs:
  ci-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: |
            go test -v example/*.go
            go test -v sdk/*.go

  # sonarcloud:
  #   needs: ci-test
  #   runs-on: self-hosted

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #           fetch-depth: 0 

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #           go-version: 1.17

  #     - name: Create Coverage Reports
  #       run: |
  #           git config --global url."https://${{ secrets.ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com"
  #           go clean --testcache
  #           echo "Run on Example"
  #           go test -v -race -coverprofile ./example/tmp/coverage.out -json ./example/*.go >> ./example/tmp/report.json
  #           echo "Run on SDK"
  #           go test -v -race -coverprofile ./sdk/tmp/coverage.out -json ./sdk/*.go >> ./sdk/tmp/report.json
      
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}